CREATE SEQUENCE SEQ_OT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_OT_ITEM START WITH 1 INCREMENT BY 1;

CREATE TABLE OT (
  OT_ID VARCHAR2(24) PRIMARY KEY,
  CLIENTE_ID VARCHAR2(20) NOT NULL,
  PATENTE VARCHAR2(10) NOT NULL,
  DESCRIPCION VARCHAR2(200),
  TOTAL NUMBER(12,0) DEFAULT 0 CHECK (TOTAL >= 0),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP
);

CREATE TABLE OT_ITEM (
  ITEM_ID NUMBER PRIMARY KEY,
  OT_ID VARCHAR2(24) NOT NULL,
  CONCEPTO VARCHAR2(40) NOT NULL,
  CANTIDAD NUMBER(10,2) NOT NULL CHECK (CANTIDAD > 0),
  PRECIO_UNIT NUMBER(12,0) NOT NULL CHECK (PRECIO_UNIT >= 0),
  SUBTOTAL NUMBER(12,0) GENERATED ALWAYS AS (ROUND(CANTIDAD * PRECIO_UNIT)),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_OT_ITEM__OT FOREIGN KEY (OT_ID) REFERENCES OT(OT_ID) ON DELETE CASCADE
);
