CREATE SEQUENCE SEQ_EVENT_LOG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NOTIFY_LOG START WITH 1 INCREMENT BY 1;

CREATE TABLE OT_EVENT (
  EVENT_ID NUMBER PRIMARY KEY,
  OT_ID VARCHAR2(24),
  EVENT_TYPE VARCHAR2(40) NOT NULL,
  PAYLOAD_JSON CLOB NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE NOTIFY_LOG (
  LOG_ID NUMBER PRIMARY KEY,
  OT_ID VARCHAR2(24),
  CLIENTE_ID VARCHAR2(20),
  CANAL VARCHAR2(20) CHECK (CANAL IN ('email','sms','push')),
  PAYLOAD_JSON CLOB NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
